# Generated by Django 5.0.1 on 2025-07-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('has_power', models.BooleanField(default=False)),
                ('near_window', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='cafe.cafe')),
            ],
        ),
    ]
