# Generated by Django 5.2.3 on 2025-07-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_has_wifi_cafe_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
