# Generated by Django 5.2.3 on 2025-07-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_rename_keyword_cafe_keywords'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='embeddings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='tag.tag'),
        ),
    ]
