# Generated by Django 5.2.3 on 2025-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cafe_embeddings_alter_cafe_keywords'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keyword', to='tag.tag'),
        ),
    ]
